---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

commonLabels:
  app.kubernetes.io/name: kubestate-metrics

images:
  - name: kubestate-metrics
    newName: k8s.gcr.io/kube-state-metrics/kube-state-metrics
    newTag: "v2.4.2"
  - name: kubestate-rbacproxy
    newName: quay.io/brancz/kube-rbac-proxy
    newTag: "v0.11.0"

...
