---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml

  - service.yml
  - deployment.yml

  - servicemonitor.yml
  - prometheusrule.yml

images:
  - name: kubestate-metrics
    newName: k8s.gcr.io/kube-state-metrics/kube-state-metrics
    newTag: "v2.6.0"
  - name: kubestate-rbacproxy
    newName: quay.io/brancz/kube-rbac-proxy
    newTag: "v0.13.1"

...
